task_path: /Users/naomichi/Projects/nichigas-sandbox/config/deploy/development.yml
scheduled_task_path: /Users/naomichi/Projects/nichigas-sandbox/config/deploy/development.yml
cluster: sandbox
service: development
scheduled_task_rule: curl
scheduled_task_target_id: worker
